name: morbegno
favicon: null
layout_spectrum: 0.9311290706973523
typography_spectrum: 0.14471815968863666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.45599568518809974
  lightness: 0.6053667711094022
  saturation: 0.801202085101977
  rhythmicContrast: 0.6806125689763576
purpose: []
