name: morbegno
favicon: null
layout_spectrum: 0.34477
typography_spectrum: 0.14471815968863666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#c3c4c3'
    - '#829e8f'
    - '#3f5c60'
  brandStrength: 0.0625
  lightness: 0.6053667711094022
  saturation: 0.801202085101977
  rhythmicContrast: 0.6806125689763576
purpose: []
